default_platform(:ios)

platform :ios do
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY"],
      duration: 1200,
      in_house: false,
      is_key_content_base64: true
    )

    # Use the absolute root path provided by GitHub Actions
    workspace = ENV["GITHUB_WORKSPACE"] || "."
    ipa_path = Dir["#{workspace}/build/export/*.ipa"].first

    UI.user_error!("No IPA found in #{workspace}/build/export") unless ipa_path

    upload_to_testflight(
      ipa: ipa_path,
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end