lane :release do
  api_key = app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_API_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_API_KEY"],
    duration: 1200,
    in_house: false,
    is_key_content_base64: true
  )

  workspace = ENV["GITHUB_WORKSPACE"] || "."
  ipa_files = Dir["#{workspace}/build/export/*.ipa"]

  UI.user_error!("No IPA found") if ipa_files.empty?
  ipa_path = ipa_files.max_by { |f| File.mtime(f) }

  upload_to_testflight(
    ipa: ipa_path,
    api_key: api_key,
    skip_waiting_for_build_processing: true
  )

  deliver(
    api_key: api_key,
    skip_binary_upload: true,
    app_identifier: "com.example.drushApp",
    skip_screenshots: true,
    skip_metadata: true,
    force: true,
    submission_information: {
      export_compliance_uses_encryption: false
    }
  )
end